{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/"
    },
    "executionInfo": {
     "elapsed": 18111,
     "status": "ok",
     "timestamp": 1696312736172,
     "user": {
      "displayName": "Jae Woo Shin",
      "userId": "00227897202452450211"
     },
     "user_tz": -540
    },
    "id": "p5Kcsi1O2GXr",
    "outputId": "3014524e-453a-44ad-c8cf-b42fa45bc5a0"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mounted at /content/drive\n"
     ]
    }
   ],
   "source": [
    "!pip install -q konlpy\n",
    "\n",
    "import random\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from tqdm import tqdm\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from konlpy.tag import Okt\n",
    "from scipy.spatial import distance\n",
    "\n",
    "def extract_tags_from_title(title):\n",
    "    tags = []\n",
    "    if any(keyword in title for keyword in _24):\n",
    "        tags.append('2024년')\n",
    "    if any(keyword in title for keyword in _23):\n",
    "        tags.append('2023년')\n",
    "    if any(keyword in title for keyword in _22):\n",
    "        tags.append('2022년')\n",
    "    if any(keyword in title for keyword in _21):\n",
    "        tags.append('2021년')\n",
    "    if any(keyword in title for keyword in _20):\n",
    "        tags.append('2020년')\n",
    "    if any(keyword in title for keyword in _19):\n",
    "        tags.append('2019년')\n",
    "    if any(keyword in title for keyword in _18):\n",
    "        tags.append('2018년')\n",
    "    if any(keyword in title for keyword in 상반기):\n",
    "        tags.append('1학기')\n",
    "    if any(keyword in title for keyword in 하반기):\n",
    "        tags.append('2학기')\n",
    "    return ', '.join(tags)\n",
    "\n",
    "def tokenizer(raw_texts):\n",
    "    return okt.morphs(raw_texts)\n",
    "    \n",
    "if __name__ == \"__main__\":\n",
    "    df = pd.read_csv('/content/drive/MyDrive/대학교/DSL/모델링 스터디/모델링 프로젝트/final/traindata.csv')\n",
    "    df['본문'] = df['본문'].fillna('내용 링크 본문 참고')\n",
    "    df['date'] = pd.to_datetime(df['등록일'], errors='coerce', format='%Y-%m-%d')\n",
    "    df['date'].fillna(pd.to_datetime(df['등록일'], errors='coerce', format='%Y.%m.%d'), inplace=True)\n",
    "    df['date'].fillna(pd.to_datetime(df['등록일'], errors='coerce', format='%y.%m.%d'), inplace=True)\n",
    "    df['date'] = df['date'].dt.date\n",
    "\n",
    "    상반기 = ['1학기', '-1', '상반기', '여름', '봄', '하절기']\n",
    "    하반기 = ['2학기', '-2', '하반기', '가을', '겨울', '동절기']\n",
    "    _24 = ['2024', '24년', '24학']\n",
    "    _23 = ['2023', '23년', '23학']\n",
    "    _22 = ['2022', '22년', '22학']\n",
    "    _21 = ['2021', '21년', '21학']\n",
    "    _20 = ['2020', '20년', '20학']\n",
    "    _19 = ['2019', '19년', '19학']\n",
    "    _18 = ['2018', '18년', '18학']\n",
    "\n",
    "    tqdm.pandas()\n",
    "    df['tags'] = df['제목'].progress_apply(extract_tags_from_title)\n",
    "\n",
    "    okt = Okt()\n",
    "    \n",
    "    df = df.dropna(axis = 0)\n",
    "    df = df.reset_index(drop = True)\n",
    "    df['cons1'] = df['작성자'] + ' ' + df['제목'] + ' ' + df['태그'] + ' ' + df['date'].astype('str') + ' ' + df['본문']\n",
    "\n",
    "    vectorizer = TfidfVectorizer(tokenizer=tokenizer)\n",
    "    \n",
    "    tfidf_matrix = vectorizer.fit_transform(df['cons1']).toarray()\n",
    "\n",
    "    keywords = vectorizer.get_feature_names_out()\n",
    "    tf_idf_matrix = tfidf_matrix\n",
    "    tfidf_matrix = tf_idf_matrix\n",
    "\n",
    "    keyword_bias = '''대회\n",
    "    공모전\n",
    "    인턴\n",
    "    채용\n",
    "    교환\n",
    "    장학\n",
    "    기숙사\n",
    "    졸업\n",
    "    복수전공\n",
    "    복학\n",
    "    휴학\n",
    "    성적\n",
    "    신청\n",
    "    변경\n",
    "    철회\n",
    "    축제\n",
    "    등록\n",
    "    셔틀\n",
    "    학식\n",
    "    AI\n",
    "    창업\n",
    "    학사\n",
    "    일정\n",
    "    '''\n",
    "    \n",
    "    keyword_bias_list = keyword_bias.strip().split('\\n')\n",
    "    \n",
    "    keywords = vectorizer.get_feature_names_out()\n",
    "    \n",
    "    # Apply bias to the keyword in the TF-IDF matrix\n",
    "    weight = 2.0  # Define a weight > 1 to bias the keyword\n",
    "    for keyword in keyword_bias_list:\n",
    "        # 토크나이즈\n",
    "        tokens = tokenizer(keyword)\n",
    "    \n",
    "        # 각 토큰에 대한 인덱스를 찾아 TF-IDF 행렬의 가중치 조절\n",
    "        for token in tokens:\n",
    "            keyword_indices = np.where(keywords == token)[0]\n",
    "            print(f\"{token} : {keyword_indices}\")\n",
    "            if keyword_indices.size > 0:\n",
    "                keyword_index = keyword_indices[0]\n",
    "                tfidf_matrix[:, keyword_index] *= weight\n",
    "\n",
    "    date_bias = '''\n",
    "    2023\n",
    "    2022\n",
    "    2021\n",
    "    2020\n",
    "    2019\n",
    "    2018\n",
    "    2017\n",
    "    2016\n",
    "    '''\n",
    "\n",
    "    date_bias_list = date_bias.strip().split('\\n')\n",
    "    \n",
    "    keywords = vectorizer.get_feature_names_out()\n",
    "    \n",
    "    # Apply bias to the keyword in the TF-IDF matrix\n",
    "    weight = 4.0  # Define a weight > 1 to bias the keyword\n",
    "    for date_bias in date_bias_list:\n",
    "        # 토크나이즈\n",
    "        tokens = tokenizer(date_bias)\n",
    "    \n",
    "        # 각 토큰에 대한 인덱스를 찾아 TF-IDF 행렬의 가중치 조절\n",
    "        for token in tokens:\n",
    "            keyword_indices = np.where(keywords == token)[0]\n",
    "            print(f\"{token} : {keyword_indices}\")\n",
    "            if keyword_indices.size > 0:\n",
    "                keyword_index = keyword_indices[0]\n",
    "                tfidf_matrix[:, keyword_index] *= weight\n",
    "\n",
    "    major_bias = '''\n",
    "    응용통계학\n",
    "    경제학\n",
    "    인공지능\n",
    "    컴퓨터과학\n",
    "    상경\n",
    "    '''\n",
    "\n",
    "    keyword_bias_list = major_bias.strip().split('\\n')\n",
    "    \n",
    "    keywords = vectorizer.get_feature_names_out()\n",
    "    \n",
    "    # Apply bias to the keyword in the TF-IDF matrix\n",
    "    weight = 2.0  # Define a weight > 1 to bias the keyword\n",
    "    for major_bias in keyword_bias_list:\n",
    "        # 토크나이즈\n",
    "        tokens = tokenizer(major_bias)\n",
    "    \n",
    "        # 각 토큰에 대한 인덱스를 찾아 TF-IDF 행렬의 가중치 조절\n",
    "        for token in tokens:\n",
    "            keyword_indices = np.where(keywords == token)[0]\n",
    "            print(f\"{token} : {keyword_indices}\")\n",
    "            if keyword_indices.size > 0:\n",
    "                keyword_index = keyword_indices[0]\n",
    "                tfidf_matrix[:, keyword_index] *= weight\n",
    "\n",
    "    iterations = 30\n",
    "    q_string_1 = [\"AI 공모전 2023\"]\n",
    "    q_vec = vectorizer.transform(q_string_1).toarray()\n",
    "    q_dist = [distance.cosine(q_vec.ravel(), t.ravel()) for t in tfidf_matrix]\n",
    "    closest_index = sorted(range(len(q_dist)), key=lambda k: q_dist[k])[1:]\n",
    "    results_1 = df['제목'].loc[closest_index[:iterations]]\n",
    "    q_string_2 = [\"인공지능 공모전 2023\"]\n",
    "    q_vec = vectorizer.transform(q_string_2).toarray()\n",
    "    q_dist = [distance.cosine(q_vec.ravel(), t.ravel()) for t in tfidf_matrix]\n",
    "    closest_index = sorted(range(len(q_dist)), key=lambda k: q_dist[k])[1:]\n",
    "    results_2 = df['제목'].loc[closest_index[:iterations]]\n",
    "\n",
    "    count = 0\n",
    "    for i in results_1.index:\n",
    "      for j in results_2.index:\n",
    "        if i == j:\n",
    "          count += 1\n",
    "    print(\"Count : \", count)\n",
    "    print(\"Iterations : \", iterations)\n",
    "    print(f\"Similarity Rate between {q_string_1} and {q_string_2} : {count / iterations * 100} %\")"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "T4",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
